### PR TITLE
Replace deprecated trollop with its replacement: optimist gem; update out-of-date gems; update travis ruby branches

### PR DESCRIPTION
**Pull request by philCryoport**
Our app relies on minitest_to_rspec.  Recently we did a completely fresh install and got the following message from bundler:

> Post-install message from trollop:
> !    The 'trollop' gem has been deprecated and has been replaced by 'optimist'.
> !    See: https://rubygems.org/gems/optimist
> !    And: https://github.com/ManageIQ/optimist

### CODE REVIEW

**Comment by philCryoport** [comment]
16_stabby_lambda appears to be the only remaining issue...

**Comment by philCryoport** [comment]
@jaredbeck I have to focus on something else at this point.  I'm a bit of a Ruby n00b as well, so I'm a bit lost as to how to fix the issue.  If you or someone else has time, please suggest what needs to be fixed here.

**Comment by jaredbeck** [comment]
Hi Phil, Thanks for working on this. 

I think you were trying to do too much at once by upgrading dependencies like rubocop, *and* trying to fix its new offenses, *and* switching to `optimist`.

I've upgraded some dependencies, including rubocop, and the build is passing. Please rebase your branch and try again. Now, you should be able to focus on `optimist`.

Thanks!

**Comment by jaredbeck** [comment]
Closed via https://github.com/jaredbeck/minitest_to_rspec/pull/29

Thanks for your work on this, Philip!

**Pull request closed without merging**
